server:
  port: 8080
  servlet:
    context-path: /api/contabilidad
management:
  server:
    servlet:
      context-path: /api/contabilidad
spring:
  application:
    name: contabilidad-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher